# This is a basic workflow to help you get started with Actions

name: Run Script

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies
      - run: pip install -r requirements.txt

      # Runs a single command using the runners shell
      - name: Run Discord Processor Script
        run: python process_requests.py
        env:
          TOKEN: ${{ secrets.TOKEN }}
          API_URL: ${{ secrets.API_URL }}
          APIKEY: ${{ secrets.APIKEY }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          
